### ISSUE TITLE
New resources

### ISSUE THREAD

**Issue by mariuszmichalowski** [danielhoherd/tech-notes#2]
I wanted to let you know that we recently published two posts that could be a useful addition to your links: https://github.com/danielhoherd/tech-notes/blob/gh-pages/kubernetes/index.html

https://spacelift.io/blog/kubernetes-cheat-sheet - Kubernetes Cheat Sheet – 15 Kubectl Commands & Objects
https://spacelift.io/blog/kubernetes-best-practices - 15 Kubernetes Best Practices Every Developer Should Know

Let me know what you think about it:)

**Comment by danielhoherd** [comment]
Great content. I'll consider adding it.

**Comment by mariuszmichalowski** [comment]
Thanks!
